spring:
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库账号
    password: 31415926
    #数据库密码
    username: root
    #连接数据库地址
    url: jdbc:mysql://localhost:3306/psbc?serverTimezone=UTC

#端口号
server:
  port: 8061

